# Generated by Django 5.2.4 on 2025-07-11 12:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Timestamp da Leitura Bruta')),
                ('voltage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tensão (V)')),
                ('current', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Corrente (A)')),
                ('active_power', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Potência Ativa (W)')),
                ('power_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Fator de Potência')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Processado?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sensor_data', to='pages.energyprofiles')),
            ],
            options={
                'verbose_name': 'Dado Bruto do Sensor',
                'verbose_name_plural': 'Dados Brutos dos Sensores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
