# Generated by Django 4.2.9 on 2025-07-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecatalog',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='devicecatalog',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='devicecatalog',
            name='tempo_uso_semanal',
        ),
        migrations.RemoveField(
            model_name='devicecatalog',
            name='uso_medio_diario_horas',
        ),
        migrations.RemoveField(
            model_name='devicecatalog',
            name='vida_util_estimativa',
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='annual_kwh_consumption',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Consumo anual estimado em kwh para este dispositivo no perfil.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='consumption_kwh_per_day',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Consumo diário calculado (kWh/dia) para este dispositivo no perfil', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='daily_kwh_consumption',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Consumo diário estimado em kWh para este dispositivo no perfil.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Dias da semana em que o dispositivo é usado (ex: MON,QUA,SEX)', max_length=50, null=True, verbose_name='Dias da Semana de Uso'),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='monthly_kwh_consumption',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Consumo mensal estimado em kWh para este dispositivo no perfil.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='tempo_uso_semanal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tempo de Uso Semanal (horas)'),
        ),
        migrations.AddField(
            model_name='profiledevices',
            name='vida_util_estimativa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil Estimada (anos)'),
        ),
        migrations.AlterField(
            model_name='profiledevices',
            name='hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uso Médio Diário (horas)'),
        ),
        migrations.AlterField(
            model_name='profiledevices',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Quantidade'),
        ),
    ]
