# Generated by Django 4.2.9 on 2025-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_devicecatalog_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyreading',
            name='measurement_type',
            field=models.CharField(choices=[('SIMPLES', 'Consumo Simples (Total)'), ('PFP', 'Consumo (Ponta/Fora Ponta)'), ('DEMANDA', 'Demanda e Consumo (Grupo A)')], default='SIMPLES', max_length=10, verbose_name='Tipo de Medição'),
        ),
    ]
