# Generated by Django 4.2.9 on 2025-07-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_energyreading_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodels',
            name='additional_params',
            field=models.JSONField(blank=True, help_text="Para configurações avançadas, ex: {'changepoint_prior_scale': 0.05}", null=True, verbose_name='Parâmetros Adicionais (JSON)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='daily_seasonality',
            field=models.BooleanField(default=False, verbose_name='Sazonalidade Diária (Prophet)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='data_source',
            field=models.CharField(choices=[('readings', 'Leituras de Energia (EnergyReading)'), ('billing', 'Faturas (BillingRecord)')], default='readings', max_length=10, verbose_name='Fonte de Dados para Treinamento'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='default_forecast_horizon',
            field=models.IntegerField(default=30, verbose_name='Horizonte de Previsão Padrão (dias)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='include_brazil_holidays',
            field=models.BooleanField(default=True, verbose_name='Incluir Feriados Nacionais (Prophet)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='last_accuracy_score',
            field=models.JSONField(blank=True, null=True, verbose_name='Últimas Métricas de Acurácia (JSON)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='model_type',
            field=models.CharField(choices=[('UPLOAD', 'Arquivo Externo (Upload)'), ('LINEAR', 'Regressão Linear Simples (Automático)'), ('PROPHET', 'Prophet (Automático)')], default='LINEAR', max_length=10, verbose_name='Tipo de Modelo'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='seasonality_mode',
            field=models.CharField(choices=[('additive', 'Aditiva'), ('multiplicative', 'Multiplicativa')], default='multiplicative', max_length=15, verbose_name='Modo de Sazonalidade (Prophet)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='weekly_seasonality',
            field=models.BooleanField(default=True, verbose_name='Sazonalidade Semanal (Prophet)'),
        ),
        migrations.AddField(
            model_name='predictionmodels',
            name='yearly_seasonality',
            field=models.BooleanField(default=True, verbose_name='Sazonalidade Anual (Prophet)'),
        ),
    ]
