# Generated by Django 4.2.9 on 2025-07-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_predictionmodels_additional_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodels',
            name='data_source',
            field=models.CharField(choices=[('readings', 'Leituras de Energia (EnergyReading)'), ('billing', 'Faturas (BillingRecord)'), ('devices', 'Consumo Agregado de Dispositivos'), ('predictions', 'Previsões Anteriores (Feedback Loop)'), ('quality', 'Registros de Qualidade de Energia'), ('goals', 'Metas de Consumo'), ('alerts', 'Histórico de Alertas de Consumo'), ('weather', 'Dados Climáticos (Ex: Temperatura)'), ('solar', 'Geração Solar (se aplicável)'), ('occupancy', 'Dados de Ocupação (Comercial)'), ('events', 'Calendário de Eventos Especiais'), ('simulation', 'Dados de Simulação')], default='readings', max_length=20, verbose_name='Fonte de Dados para Treinamento'),
        ),
        migrations.AlterField(
            model_name='predictionmodels',
            name='model_type',
            field=models.CharField(choices=[('UPLOAD', 'Arquivo Externo (Upload)'), ('LINEAR', 'Regressão Linear Simples (Automático)'), ('PROPHET', 'Prophet (Automático)'), ('RF_REG', 'Florestas Aleatórias (Regressão)'), ('TF_REG', 'Rede Neural - Keras/TensorFlow (Regressão)'), ('LOGISTIC', 'Regressão Logística (Classificação)'), ('DT_CLASS', 'Árvore de Decisão (Classificação)'), ('KMEANS', 'K-Means (Clusterização)'), ('GMM', 'Misturas de Gaussianas (Clusterização)'), ('APRIORI', 'Apriori (Regras de Associação)'), ('BAYESIAN', 'Inferência Bayesiana'), ('KNN', 'K-Vizinhos Mais Próximos (K-NN)')], default='LINEAR', max_length=10, verbose_name='Tipo de Modelo'),
        ),
    ]
